name: 'Deploy-to-Grading'
description: 'This action will setup and execute the Deploy-to-Grading pipeline.'
runs:
  using: 'composite'
  steps:
    - run: ls && ./scripts/deploy-to-grading
      shell: bash
