name: 'Deploy-to-Grading'
description: 'This action will setup and execute the Deploy-to-Grading pipeline.'
runs:
  using: 'composite'
  steps:
    - run: ls ${{ github.action_path }} && sh ${{ github.action_path }}/scripts/deploy-to-grading
      shell: bash
