name: 'Deploy-to-Grading'
description: 'This action will setup and execute the Deploy-to-Grading pipeline.'
runs:
  using: 'composite'
  steps:
    - run: python3 ${{ github.action_path }}/scripts/deploy_to_grading.py
      env: 
        D2G_PATH: ${{ github.action_path }}
      shell: bash
